#! /usr/bin/env bash
# do-build <platform> <results-dir> This script is used to generate a binary to release.

if [ $# -ne 2 ]; then
	echo "wrong number of arguments"
	exit 1
fi

PLATFORM=$1
RESULTS_DIR=$2

pushd "u-boot-1.1.6"

if [ "$PLATFORM" == "leanXcam" ]; then
	make bf537-leanxcam_config || exit $?
elif [ "$PLATFORM" == "indXcam" ]; then
	exit 1 # do not use, mockup!
	make bf537-indxcam_config || exit $?
else
	echo "Unknown architecture!"
	exit 1
fi

make || exit $?

popd

cp "u-boot-1.1.6/u-boot.ldr" "$RESULTS_DIR/u-boot.ldr" || exit $?
