#############################################################################
#
#                   Copyright (C) 1996 SciTech Software.
#                           All rights reserved.
#
# Descripton:   Makefile for UniVBE(tm), UniPOWER(tm), UVBELib(tm) and
#               DPMSLib library files. Requires Borland C++ 4.52 to build
#               some components.
#
# $Date: 2007/12/17 10:20:58 $ $Author: mberner $
#
#############################################################################

CFLAGS += -DTESTING_GTF

gtfcalc$E:  gtfcalc$O

.INCLUDE: "$(SCITECH)/makedefs/common.mk"
